<?php
include '../fpdf/fpdf.php';
include '../koneksi.php';
include 'session.php';
$tgl = date('d-M-Y');
$pdf = new FPDF();
$pdf->Open();
$pdf->addPage();
$pdf->setAutoPageBreak(false);
$pdf->setFont('Arial','',12);
$judul = "PT. Tugas Akhir";
$judul2 = "Laporan Semua Barang";
$pdf->Cell(0,10,$judul,'0','1','C');
$pdf->Cell(0,30,$judul2,'0','1','L');
$row = 0;
$yi = 50;
$ya = 44;
$pdf->setFont('Arial','',9);
$pdf->setFillColor(222,222,222);
$pdf->setXY(10,$ya);
$pdf->CELL(6,6,'NO',1,0,'C',1);
$pdf->CELL(35,6,'Jenis Barang',1,0,'C',1);
$pdf->CELL(40,6,'kode Barang',1,0,'C',1);
$pdf->CELL(40,6,'Merk Barang',1,0,'C',1);
$pdf->CELL(40,6,'No Seri',1,0,'C',1);
$pdf->CELL(35,6,'Status',1,0,'C',1);
$ya = $yi + $row;
$sql = mysql_query("SELECT * FROM barang INNER JOIN jenis_brg ON barang.id_jenis=jenis_brg.id_jenis ORDER BY barang.id DESC limit 0,35");
$i = 1;
$no = 1;
$max = 31;
$row = 6;
while($data = mysql_fetch_array($sql)){
$pdf->setXY(10,$ya);
$pdf->setFont('arial','',9);
$pdf->setFillColor(255,255,255);
$pdf->cell(6,6,$no,1,0,'C',1);
$pdf->cell(35,6,$data['nama'],1,0,'C',1);
$pdf->cell(40,6,$data['kode_brg'],1,0,'C',1);
$pdf->CELL(40,6,$data['merk_brg'],1,0,'C',1);
$pdf->CELL(40,6,$data['no_seri'],1,0,'C',1);
$pdf->CELL(35,6,$data['status_brg'],1,0,'C',1);
$ya = $ya+$row;
$no++;
$i++;
}
$oe = "Cimahi, ".$tgl;
$eo = $b['nama_depan']." ".$b['nama_belakang'];
$pdf->Cell(0,27,$oe,'0','1','R');
$pdf->Cell(187,10,$eo,'10','1','R');
$pdf->output();
?>